# Generated by Django 5.1.1 on 2024-09-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='job_title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
    ]
